yeoman/environment

- lib/store.js
- package.json
- test/environment.js
- test/store.js
It's huge and slows down both install and startup time for `yo`.
> remove `yeoman-generator` dependency - fixes #21

- lib/environment.js
* This bug is not an io.js issue but really an issue with any module
path that has more than one '.js' in its path.  Since io.js is
typically installed into a directory called 'io.js', if you have a
generator path of
/path/to/io.js/node_modules/lib/generators/yo/index.js, the first
occurance of '.js' was replaced instread of the '.js' in 'index.js'.
Fixes #30
> Fix namespace resolution for paths with more than one '.js' in it

- lib/environment.js
* Instead of blindly turning a file extension into a RegExp, we now
escape the input using `escape-string-regexp`.  Since it was already
in use, it was a non-issue.
* This is a follow up to #31.  #31 fixed the immediate problem but left
yeoman-environment in the same state it was before.  This should make
namespace resolution safer.
> Make namespace resolution safer

- lib/environment.js
- test/environment.js
This solves an issue where `package.json` would be resolved instead of `package/index.js`. It forces all module resolutions to directories. Fix suggested by @SBoudrias.
> Environment.prototype.resolveModulePath() resolves only directories if no file extension specified.

- lib/environment.js
- test/environment.js
Fix https://github.com/yeoman/environment/issues/20
> Add `Environment.namespaceToName()` method

- lib/util/log.js
> Don't print `\n` when no argument in `write()`

- lib/environment.js
Particularly when using a command like `yo foo:bar`
> Fix traceback displayed when using invalid generator name

- lib/environment.js
- test/environment.js
The existing method of removing sub-generator `lookup` patterns from the path created unexpected results in a few corner cases:
- `my-lib/generators/app` => `my-:app`, instead of `my-lib:app`
- `my.lib/generators/app` => `mylib:app`, instead of `my.lib:app`
- `test/generators/generators-thing` => `test:-thing`
> fix(env#namespace): only remove `lookups` that match full directory name

- lib/resolver.js
- test/resolver.js
As discussed in #59
Added tests for `with NVM_PATH` / `without NVM_PATH` that checks the same things `NODE_PATH` checks, not sure if it's good enough but it covers the case of NVM_PATH being defined.
> Add NVM prefix if NVM_PATH is defined

- package.json
Untildify 3.0.0 breaks compatibility with Node 0.10 and 0.12. Downgrading to
2.0.0 restores it.
Fixes #61
> Downgrade untildify

- lib/environment.js
- test/environment.js
Hi!
This pull request makes it possible to say:
```
yo D:\src\projects\vscode-generator-code\generators\app
```
Useful for debugging of generators.
Thank you,
Mykola.
> Improved handling of win32 abs paths when executing a generator by path.

- lib/resolver.js
Have a problem with lookup function on Mac OS.
getNpmPaths is looking for generators in node_modules at
'/usr/lib/node_modules' path, but also there is another path for
node_modules on mac: '/usr/local/lib/node_modules'.
> getNpmPaths default path for Mac OS

- lib/resolver.js
Closes https://github.com/yeoman/generator/issues/1032
> Add support for yarn linked generators

- lib/environment.js
- test/environment.js
This PR addresses #75 by allowing quote-mark separated command line arguments. It changes the splitting of argument strings to a 2-step process: it first splits the string apart by quotes (any part matching "*"), and then splits parts of the string up further if they are not part of a quote.
> Support for multi-word command line arguments

- lib/environment.js
- test/environment.js
- test/fixtures/generator-module/generators/app/index.js
- test/fixtures/generator-module/package.json
If generators are exported as modules using `exports default ...` or `exports.default = ...` Yeoman fails to recognize the generator exists because it does not look for it in the `default` property of the module. Only using `module.exports` the generator is recognized, this makes it impossible to run generators transpiled from ES6+. It is also hard to recognize the reason why it fails.
Added 2 regression tests and the fix for this issue.
> Get and run generators exported with exports default

- lib/environment.js
- test/environment.js
Fix generator error handling (Fix #89)
When a generator's run emits an 'error' event, there is no handler for it, thus causing the application to crash.
In some cases the error is also passed to the callback of the run method, which can cause double handling of the error event.
The solution is to handle the event of the generator and call the callback with it, while ensuring the callback is only being called once.
If no callback was passed, keep backwards behavior and let the emitted error crash the application (as it is not handled). This is the expected behaviour when using the yo cli tool
> Fix generator error handling (Fix #89)

- lib/environment.js
- test/environment.js
In the case of a module generator, the namespace and resolved properties
were being lost as the instantiate function expects them to be attached
as properties of the constructor function. This commit ensures they
are being passed where the instantiate function expects to find them.
For issue #107
> Ensure that the namespace and resolved properties are passed

- lib/resolver.js
- test/resolver.js
I've noticed that, when building a list of generators, `yo` will list any globally-installed generators, in addition to any it can find in local `node_modules` directories. I understand why it does this, of course, but there are situations where I'd like to change this behavior and only display local generators, and I'm sure I"m probably not alone in this.
For my particular use case, I'm creating NPM package projects, each with a script that runs *yo* to pick from a list of generators that developers can use to quickly add files for new classes, tests, and so on.
As any veteran NPM user can attest, installing both `yo` and the project-specific generators *locally* is far more ideal than trying to have all of these projects share the same copies of these dependencies as globally-installed …
> Add localOnly argument to generator lookup

- test/resolver.js
When npm test is interrupted with ^C, next time it will fail.
> Add verification to test.

- lib/environment.js
When a generator fails to instantiate we probably should catch and behave like not found error.
> Catch generator's instantiation errors.

- lib/environment.js
- package-lock.json
- package.json
When a generator fails, an error event is emitted on a scheduled task, and due to https://nodejs.org/api/events.html#events_error_events, an error will be thrown on a composed generator (no error event listener is registered).
The error will be treated directly by node.js killing the process.
This reverts the old behaviour where no error event listener is registered.
> Revert yeoman-environment behaviour.

- lib/resolver.js
- test/resolver.js
Fixes lookup outside node_modules repository.
> Use relative path to calculate namespace.

- lib/environment.js
So typical TypeScript projects using `src`/`dist` folders work out of the box... :)
> Add "dist/generators" in lookups

- lib/util/conflicter.js
- test/conflicter.js
- test/environment.js
- bail requires `force=false`.
- should not force ignoreWhitespace.
- print conflicted file at error.
> Conflicter improvements

- lib/environment.js
Error message when generator was not found hinted invalid command: `yo` to list all generators.
With [yo](https://github.com/yeoman/yo) v2 or newer the command should be: `yo --generators. See [yo/lib/usage](https://github.com/yeoman/yo/blob/ea5e36b44af14e6930b4b8c436665533e094fe3c/lib/usage.txt#L9).
> fix: error message when generator not found

- lib/environment.js
Fix typo in progress indicator for transforms.
> Fix typo in file transform

- src/environment-base.ts
- test/generator-features.js
- fix watch for package.json changes.
> add support to custom package.json install and watch.

- src/environment-base.ts
- test/environment.js
depends on  yeoman/yeoman-api#6
required by  jhipster/generator-jhipster#25445
This PR allows a callback function as an option for `ComposeOptions.schedule`
The function receives the generator instance as the parameter and must return a boolean that will decide the scheduling. A true return value schedules the generator to be run under environment:run loop and a false queues the generator tasks immediately.
usage:
```
env.composeWith('hello:world', { schedule: (generator) => {
// some code to decide the scheduling option
return generator.immediate;
}});
```
> add callback function support for generator scheduling

- src/package-manager.ts
- test/package-manager.js
[Bun](https://bun.sh/) is an all-in-one JavaScript runtime & toolkit designed for speed, complete with a bundler, test runner, and Node.js-compatible package manager.
> add bun support as a package manager

- src/store.ts
- test/environment.js
> docs: correct provide(s) typo in error
