yeoman/environment

- lib/environment.js
Closes yeoman/yo#388
Error message before:
Error message after:
> Improve error message when generator not found

- .travis.yml
- package.json
> Bump minimum supported `node` version to `node@4`.

- lib/resolver.js
fix https://github.com/yeoman/environment/issues/84
> search default system paths last

- lib/resolver.js
> fix yarn paths on Windows

- lib/resolver.js
- package.json
> fix: update paths for yarn v1.5.1+

- lib/resolver.js
Limit recursive lookups when searching for generators in namespace folders.
> Limit recursiveness

- lib/environment.js
- lib/resolver.js
- test/fixtures/generator-environment-extend/app/index.js
- test/fixtures/generator-environment-extend/package.json
- test/resolver.js
This will make easy to create generators that extends other generators using namespace.
> Add support to lookup a generator without an environment instance.

- lib/environment.js
- lib/resolver.js
- lib/store.js
- test/environment.js
- test/resolver.js
With packagePath will be possible to get the generator's package.json.
> Store package info when performing a lookup.

- lib/environment.js
- test/resolver.js
> Add parameter to lookupGenerator to return packagePath instead of

- lib/adapter.js
Don't regenerate the differences if it exists.
> Add changes parameter to diff.

- lib/resolver.js
- test/resolver.js
- Add a filter that removes not repository paths from lookup.
- Add an option to customize the paths to look for generators.
> Improve lookup.

- .github/workflows/stale.yml
- .github/workflows/triage.yml
- set initial label.
- close stale issues.
> Add github actions:

- .github/workflows/ci.yml
Testing against 2.0.5 and latest is enough
> Remove CI test for generator 3 and 4

- lib/resolver.js
- test/resolver.js
Should use packagePaths instead.
> Revert pass-thought npmPath as packagePath.

- lib/environment.js
- test/environment.js
Implement multi-generator shared options that will passed to instantiated generators by default.
> Implement sharedOptions and sharedData.

- lib/resolver.js
- Add return to lookup and _tryRegistering
- This can conflict with making lookup async (I think we should make an async version instead of making lookup async).
> Change lookup to return structure with package details

- lib/environment.js
> Add missing try/catch on require.resolve and remove js extension to fix ts support.

- package.json
> Add npm test scripts shortcuts.

- lib/resolver.js
Lookup has become really powerful to lookup packages and modules.
This PR extracts lookup to a new independent object.
> Implement an independent packageLookup.

- lib/composability.js
- lib/environment.js
- lib/namespace-composability.js
- lib/namespace.js
- lib/util/repository.js
- package.json
- test/environment.js
- test/flags.js
- test/namespace.js
- test/resolver.js
Fixes https://github.com/yeoman/environment/issues/139
> Implement advanced namespace specification 

- lib/environment.js
- lib/generators.js
- lib/namespace.js
- package.json
- test/fixtures/generator-mocha/index.js
- test/generators.js
- test/namespace.js
Implements getGeneratorInstance and rootGenerator for composition.
> Implement instance register.

- lib/resolver.js
- test/resolver.js
Fixes https://github.com/yeoman/environment/issues/209
> Fix regression with linked node_modules.

- lib/namespace.js
- test/namespace.js
* Allow version without trailing @
* Implement namespaceFromPackageName
* Add toString()
> Improvements to namespace

- package-lock.json
- package.json
This reverts commit 9c1cab5f429d2666d5e676b33aaeac7d5c12d139.
> Revert "Bump yeoman-generator to 4.10.1"

- package-lock.json
- package.json
A stand alone generator can control mem-fs/mem-fs-editor versions.
> Add peer dependency on mem-fs and mem-fs-editor.

- .github/workflows/ci.yml
Test old generators versions with ubuntu only
> Reduce workflow matrix

- .github/workflows/ci.yml
- lib/util/binary-diff.js
- package-lock.json
- package.json
- Having a dependency not forward safe can make a package broken in the future. Drop istextorbinary.
> Implement custom isBinary function.

- lib/spawn-command.js
- test/spawn-command.js
Fixes https://github.com/yeoman/environment/issues/307
> Fix spawn command context.

- lib/environment.js
Closes https://github.com/yeoman/environment/issues/313.
> Fix assertion.

- lib/environment.js
- test/environment.js
- test/fixtures/generator-common-js/generators/cjs/index.cjs
- test/fixtures/generator-esm/generators/app/index.js
Constructor cannot be async, so execute _postConstruct after instantiated.
> Add support to _postConstruct (async).

- lib/environment.js
- lib/util/conflicter.js
- lib/util/out-of-order-transform.js
- lib/util/transform.js
- package-lock.json
- package.json
- Deprecate out-of-order in favor of p-transform package.
> Fix Node 16 transform behavior change.

- lib/environment.js
- lib/util/conflicter.js
- lib/util/transform.js
- test/conflicter.js
Force is saved to the temporary status if exists.
Closes https://github.com/yeoman/environment/issues/324
> Add conflicterStatus to checkConflict.

- lib/environment.js
- test/environment.js
Closes https://github.com/yeoman/environment/issues/366
> Simplify `namespace()` using slash and resolve repository namespaces.

- lib/util/conflicter.js
Fixes https://github.com/yeoman/environment/issues/371
> Fix outdated force check.

- package-lock.json
- package.json
Fixes https://github.com/yeoman/environment/issues/420
> add dependency on isbinaryfile

- lib/environment.js
- lib/util/repository.js
give register when create Arborist
> feat: pass register in constructor

- lib/environment.js
- lib/util/repository.js
use correct registry prop for arborist
> fix: use correct registry prop for arborist

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/gh_pages.yml
- .github/workflows/integration.yml
- .github/workflows/lock-maintenance.yml
- .github/workflows/scorecards.yml
- .github/workflows/stale.yml
- .github/workflows/triage.yml
This PR included all the changes from #577 and some improvements (3f87a7a)
- Related: https://github.com/yeoman/.github/issues/1
- Closes #577
> ci: apply security best practices

- src/commit.ts
- test/command.js
- test/environment.js
- test/generator-features.js
- test/package-manager.js
> lint files

- .github/workflows/codeql.yml
- .github/workflows/gh_pages.yml
- .github/workflows/lock-maintenance.yml
- .github/workflows/scorecards.yml
- .github/workflows/stale.yml
> ci: apply prettier

- package-lock.json
- package.json
- src/environment-base.ts
- src/generator-lookup.ts
- tsconfig.json
> chore: bump dependencies

- src/environment-base.ts
- test/environment.js
> feat: add context map to environment

- package-lock.json
- package.json
> chore: add yeoman-generator v8 to test matrix

- .gitignore
> chore: ignore package-lock files

- .github/dependabot.yml
> chore: unlock node 20 types

- bin/bin.cjs
- eslint.config.js
- src/cli/index.ts
- src/cli/utils.ts
- src/commands.ts
- src/environment-base.ts
- src/environment-full.ts
- src/generator-lookup.ts
- src/index.ts
- src/module-lookup.ts
- src/package-manager.ts
- src/store.ts
- src/util/command.ts
- src/util/resolve.ts
- test/command.js
- test/environment.js
- test/generator-features.js
- test/helpers.js
- test/package-manager.js
- test/plugins.js
- test/resolver.js
- test/store.js
- tsconfig.json
> chore: adjusts for NodeJS native typescript

- .github/workflows/ci.yml
- test/fixtures/generator-environment-extend/app/index.js
> chore: add node 22, 23, 24 to ci

- package-lock.json
- package.json
> chore: bump typescript version

- src/composed-store.ts
- src/environment-base.ts
- src/package-manager.ts
> chore: improve types

- src/environment-full.ts
- src/util/command.ts
> fix: adjusts to commander support

- package-lock.json
- package.json
- tsconfig.json
> chore: disable skipLibCheck

- package-lock.json
- src/index.ts
> chore: recreate package-lock.json
